I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    python:
  File "game/script.rpy", line 15, in <module>
    povname = renpy.input("What is your name?", length=32, screen=hello_world)
NameError: name 'hello_world' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    python:
  File "/Applications/renpy-8.1.1-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.1.1-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    povname = renpy.input("What is your name?", length=32, screen=hello_world)
NameError: name 'hello_world' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.1.23060707
Koi 1.0
Sat Sep  2 22:43:22 2023
